# Blog
keywords: Hexo,HTML,CSS,android,Linux
author: Author Name,name@example.com
description: 咸鱼的学习📒 Lok'tar
avatar: /images/favicon.jpeg
avatar_big: /images/avator.jpg

# Social Accounts
twitter: 
rss: atom.xml
weibo: 
instagram: 
github: Caraws
facebook: 

# Comment
duoshuo: 
disqus: 
gentie: 
