# 博客关键词
keywords: hexo, HTML, CSS, Javascript, Node.js

# 作者信息
author: Cara,zzxxcclloopp@gmail.com

# 博客描述
description: 咸鱼的博客和学习笔记📒 'Lok-Tar Ogar!'.

# 右上角头像
avatar: http://ordjgqxuv.bkt.clouddn.com/cara_30/WechatIMG8.jpeg

# 评论框
gentie:

# github账号
github: Caraws
